-- Build SQLite3
--   static or shared library
--   Encryption support for Multiple Ciphers
--   Debug or Release
--   Win32 or Win64

-- Target directory for the build files generated by premake5
newoption {
  trigger     = "builddir",
  value       = "build",
  description = "Directory for the generated build files"
}

BUILDDIR = _OPTIONS["builddir"] or "build"

-- Determine version of Visual Studio action
vc_version = "";
if _ACTION == "vs2003" then
  vc_version = 7
elseif _ACTION == "vs2005" then
  vc_version = 8
elseif _ACTION == "vs2008" then
  vc_version = 9
elseif _ACTION == "vs2010" then
  vc_version = 10
elseif _ACTION == "vs2012" then
  vc_version = 11
elseif _ACTION == "vs2013" then
  vc_version = 12
elseif _ACTION == "vs2015" then
  vc_version = 14
elseif _ACTION == "vs2017" then
  vc_version = 15
elseif _ACTION == "vs2019" then
  vc_version = 16
end

is_msvc = false
msvc_useProps = false
if ( vc_version ~= "" ) then
  is_msvc = true
  msvc_useProps = vc_version >= 10
  vc_with_ver = "vc"..vc_version
end

-- Activate loading of separate props file
if (msvc_useProps) then
  premake.wxProject = true
end

-- SQLite3MultipleCiphers workspace

workspace "SQLite3MultipleCiphers"
  configurations { "Debug", "Release" }
  platforms { "Win32", "Win64" }
  location(BUILDDIR)

  if (is_msvc) then
    local wks = workspace()
    wks.filename = "SQLite3MultipleCiphers_" .. vc_with_ver
  end

  defines {
    "_WINDOWS",
    "WIN32",
    "_CRT_SECURE_NO_WARNINGS",
    "_CRT_SECURE_NO_DEPRECATE",
    "_CRT_NONSTDC_NO_DEPRECATE"
  }

  filter { "platforms:Win32" }
    system "Windows"
    architecture "x32"

  filter { "platforms:Win64" }
    system "Windows"
    architecture "x64"
    targetsuffix "_x64"

  filter { "configurations:Debug*" }
    defines {
      "DEBUG", 
      "_DEBUG"
    }
    symbols "On"

  filter { "configurations:Release*" }
    defines {
      "NDEBUG"
    }
    optimize "On"  

  filter {}

-- SQLite3 static library
project "sqlite3mc_lib"
  language "C++"
  kind "StaticLib"

  if (is_msvc) then
    local prj = project()
    prj.filename = "SQLite3MultipleCiphers_" .. vc_with_ver .. "_lib"
  else
    toolset("gcc")
  end
  makesettings { "include config.gcc" }

  files { "src/sqlite3mc.c", "src/*.h" }
  vpaths {
    ["Header Files"] = { "**.h" },
    ["Source Files"] = { "**/sqlite3mc.c", "**.def", "**.rc" }
  }
  characterset ("Unicode")
  staticruntime "On"  

  location( BUILDDIR )
  targetname "sqlite3mc"

  defines {
    "_LIB",
    "CODEC_TYPE=CODEC_TYPE_CHACHA20",
    "SQLITE_THREADSAFE=1",
    "SQLITE_DQS=0",
    "SQLITE_MAX_ATTACHED=10",
    "SQLITE_ENABLE_EXPLAIN_COMMENTS=1",
    "SQLITE_SOUNDEX=1",
    "SQLITE_ENABLE_COLUMN_METADATA=1",
    "SQLITE_SECURE_DELETE=1",
    "SQLITE_ENABLE_DESERIALIZE=1",
    "SQLITE_ENABLE_FTS3=1",
    "SQLITE_ENABLE_FTS3_PARENTHESIS=1",
    "SQLITE_ENABLE_FTS4=1",
    "SQLITE_ENABLE_FTS5=1",
    "SQLITE_ENABLE_JSON1=1",
    "SQLITE_ENABLE_RTREE=1",
    "SQLITE_ENABLE_GEOPOLY=1",
    "SQLITE_CORE=1",
    "SQLITE_ENABLE_EXTFUNC=1",
    "SQLITE_ENABLE_CSV=1",
--    "SQLITE_ENABLE_SHA3=1",
    "SQLITE_ENABLE_CARRAY=1",
--    "SQLITE_ENABLE_FILEIO=1",
    "SQLITE_ENABLE_SERIES=1",
    "SQLITE_ENABLE_UUID=1",
    "SQLITE_TEMP_STORE=2",
    "SQLITE_USE_URI=1",
    "SQLITE_USER_AUTHENTICATION=1",
-- Compatibility with official SQLite3 shell    
    "SQLITE_ENABLE_DBSTAT_VTAB=1",
    "SQLITE_ENABLE_STMTVTAB=1",
    "SQLITE_ENABLE_UNKNOWN_SQL_FUNCTION=1"
  }

  -- Intermediate directory
  if (is_msvc) then
    objdir (BUILDDIR .. "/obj/" .. vc_with_ver)
  else
    objdir (BUILDDIR .. "/obj/gcc")
  end
  -- Target directory
  filter { "configurations:Debug*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/lib/debug")
    else
      targetdir "bin/gcc/lib/debug"
    end
  filter { "configurations:Release*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/lib/release")
    else
      targetdir "bin/gcc/lib/release"
    end

-- SQLite3 shared library
project "sqlite3mc_dll"
  language "C++"
  kind "SharedLib"

  if (is_msvc) then
    local prj = project()
    prj.filename = "SQLite3MultipleCiphers_" .. vc_with_ver .. "_dll"
  else
    toolset("gcc")
  end
  makesettings { "include config.gcc" }

  files { "src/sqlite3mc.c", "src/*.h", "src/sqlite3mc.def", "src/sqlite3mc.rc" }
  filter {}
  vpaths {
    ["Header Files"] = { "**.h" },
    ["Source Files"] = { "**/sqlite3mc.c", "**.def", "**.rc" }
  }
  characterset ("Unicode")
  staticruntime "On"  

  location( BUILDDIR )
  targetname "sqlite3mc"

  defines {
    "_USRDLL",
    "CODEC_TYPE=CODEC_TYPE_CHACHA20",
    "SQLITE_THREADSAFE=1",
    "SQLITE_DQS=0",
    "SQLITE_MAX_ATTACHED=10",
    "SQLITE_SOUNDEX=1",
    "SQLITE_ENABLE_COLUMN_METADATA=1",
    "SQLITE_SECURE_DELETE=1",
    "SQLITE_ENABLE_DESERIALIZE=1",
    "SQLITE_ENABLE_FTS3=1",
    "SQLITE_ENABLE_FTS3_PARENTHESIS=1",
    "SQLITE_ENABLE_FTS4=1",
    "SQLITE_ENABLE_FTS5=1",
    "SQLITE_ENABLE_JSON1=1",
    "SQLITE_ENABLE_RTREE=1",
    "SQLITE_ENABLE_GEOPOLY=1",
    "SQLITE_CORE=1",
    "SQLITE_ENABLE_EXTFUNC=1",
    "SQLITE_ENABLE_CSV=1",
    "SQLITE_ENABLE_SHA3=1",
    "SQLITE_ENABLE_CARRAY=1",
    "SQLITE_ENABLE_FILEIO=1",
    "SQLITE_ENABLE_SERIES=1",
    "SQLITE_ENABLE_UUID=1",
    "SQLITE_TEMP_STORE=2",
    "SQLITE_USE_URI=1",
    "SQLITE_USER_AUTHENTICATION=1"
  }

  -- Intermediate directory
  if (is_msvc) then
    objdir (BUILDDIR .. "/obj/" .. vc_with_ver)
  else
    objdir (BUILDDIR .. "/obj/gcc")
  end
  -- Target directory
  filter { "configurations:Debug*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/dll/debug")
    else
      targetdir "bin/gcc/dll/debug"
    end
  filter { "configurations:Release*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/dll/release")
    else
      targetdir "bin/gcc/dll/release"
    end

-- SQLite3 Shell    
project "sqlite3mc_shell"
  kind "ConsoleApp"
  language "C++"

  if (is_msvc) then
    local prj = project()
    prj.filename = "SQLite3MultipleCiphers_" .. vc_with_ver .. "_shell"
  else
    toolset("gcc")
  end
  makesettings { "include config.gcc" }

  vpaths {
    ["Header Files"] = { "**.h" },
    ["Source Files"] = { "**.c", "**.rc" }
  }
  files { "src/sqlite3.h", "src/shell.c", "src/sqlite3mc_shell.rc" }
  characterset ("Unicode")
  staticruntime "On"  
  links { "sqlite3mc_lib" }

  location( BUILDDIR )

  defines {
    "SQLITE_SHELL_IS_UTF8=1",
    "SQLITE_USER_AUTHENTICATION=1"
  }

  -- Intermediate directory
  if (is_msvc) then
    objdir (BUILDDIR .. "/obj/" .. vc_with_ver)
  else
    objdir (BUILDDIR .. "/obj/gcc")
  end
  -- Target directory
  filter { "configurations:Debug*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/lib/debug")
    else
      targetdir "bin/gcc/lib/debug"
    end
  filter { "configurations:Release*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/lib/release")
    else
      targetdir "bin/gcc/lib/release"
    end

-- ICU support
-- SQLite3 static library with ICU support
project "sqlite3mc_libicu"
  language "C++"
  kind "StaticLib"

  if (is_msvc) then
    local prj = project()
    prj.filename = "SQLite3MultipleCiphers_" .. vc_with_ver .. "_libicu"
  else
    toolset("gcc")
  end
  makesettings { "include config.gcc" }

  files { "src/sqlite3mc.c", "src/*.h" }
  vpaths {
    ["Header Files"] = { "**.h" },
    ["Source Files"] = { "**/sqlite3mc.c", "**.def", "**.rc" }
  }
  characterset ("Unicode")
  staticruntime "On"  
  includedirs { "$(LIBICU_PATH)/include" }

  location( BUILDDIR )
  targetname "sqlite3mc_icu"

  defines {
    "_LIB",
    "CODEC_TYPE=CODEC_TYPE_CHACHA20",
    "SQLITE_THREADSAFE=1",
    "SQLITE_ENABLE_ICU=1",
    "SQLITE_DQS=0",
    "SQLITE_MAX_ATTACHED=10",
    "SQLITE_ENABLE_EXPLAIN_COMMENTS=1",
    "SQLITE_SOUNDEX=1",
    "SQLITE_ENABLE_COLUMN_METADATA=1",
    "SQLITE_SECURE_DELETE=1",
    "SQLITE_ENABLE_DESERIALIZE=1",
    "SQLITE_ENABLE_FTS3=1",
    "SQLITE_ENABLE_FTS3_PARENTHESIS=1",
    "SQLITE_ENABLE_FTS4=1",
    "SQLITE_ENABLE_FTS5=1",
    "SQLITE_ENABLE_JSON1=1",
    "SQLITE_ENABLE_RTREE=1",
    "SQLITE_ENABLE_GEOPOLY=1",
    "SQLITE_CORE=1",
    "SQLITE_ENABLE_EXTFUNC=1",
    "SQLITE_ENABLE_CSV=1",
--    "SQLITE_ENABLE_SHA3=1",
    "SQLITE_ENABLE_CARRAY=1",
--    "SQLITE_ENABLE_FILEIO=1",
    "SQLITE_ENABLE_SERIES=1",
    "SQLITE_ENABLE_UUID=1",
    "SQLITE_TEMP_STORE=2",
    "SQLITE_USE_URI=1",
    "SQLITE_USER_AUTHENTICATION=1",
-- Compatibility with official SQLite3 shell    
    "SQLITE_ENABLE_DBSTAT_VTAB=1",
    "SQLITE_ENABLE_STMTVTAB=1",
    "SQLITE_ENABLE_UNKNOWN_SQL_FUNCTION=1"
  }

  -- Intermediate directory
  if (is_msvc) then
    objdir (BUILDDIR .. "/obj/" .. vc_with_ver)
  else
    objdir (BUILDDIR .. "/obj/gcc")
  end
  -- Target directory
  filter { "configurations:Debug*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/lib/debug")
    else
      targetdir "bin/gcc/lib/debug"
    end
  filter { "configurations:Release*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/lib/release")
    else
      targetdir "bin/gcc/lib/release"
    end

-- SQLite3 shared library with ICU support
project "sqlite3mc_dllicu"
  language "C++"
  kind "SharedLib"

  if (is_msvc) then
    local prj = project()
    prj.filename = "SQLite3MultipleCiphers_" .. vc_with_ver .. "_dllicu"
  else
    toolset("gcc")
  end
  makesettings { "include config.gcc" }

  files { "src/sqlite3mc.c", "src/*.h", "src/sqlite3mc.def", "src/sqlite3mc.rc" }
  filter {}
  vpaths {
    ["Header Files"] = { "**.h" },
    ["Source Files"] = { "**/sqlite3mc.c", "**.def", "**.rc" }
  }
  characterset ("Unicode")
  staticruntime "On"  
  includedirs { "$(LIBICU_PATH)/include" }  

  filter { "platforms:Win32" }
    libdirs { "$(LIBICU_PATH)/lib" }
  filter { "platforms:Win64" }
    libdirs { "$(LIBICU_PATH)/lib64" }
  filter {}

  filter { "configurations:Debug*" }
    links { "icuind", "icuucd" }
  filter { "configurations:Release*" }
    links { "icuin", "icuuc" }
  filter {}

  location( BUILDDIR )
  targetname "sqlite3mc_icu"

  defines {
    "_USRDLL",
    "CODEC_TYPE=CODEC_TYPE_CHACHA20",
    "SQLITE_THREADSAFE=1",
    "SQLITE_ENABLE_ICU=1",
    "SQLITE_DQS=0",
    "SQLITE_MAX_ATTACHED=10",
    "SQLITE_SOUNDEX=1",
    "SQLITE_ENABLE_COLUMN_METADATA=1",
    "SQLITE_SECURE_DELETE=1",
    "SQLITE_ENABLE_DESERIALIZE=1",
    "SQLITE_ENABLE_FTS3=1",
    "SQLITE_ENABLE_FTS3_PARENTHESIS=1",
    "SQLITE_ENABLE_FTS4=1",
    "SQLITE_ENABLE_FTS5=1",
    "SQLITE_ENABLE_JSON1=1",
    "SQLITE_ENABLE_RTREE=1",
    "SQLITE_ENABLE_GEOPOLY=1",
    "SQLITE_CORE=1",
    "SQLITE_ENABLE_EXTFUNC=1",
    "SQLITE_ENABLE_CSV=1",
    "SQLITE_ENABLE_SHA3=1",
    "SQLITE_ENABLE_CARRAY=1",
    "SQLITE_ENABLE_FILEIO=1",
    "SQLITE_ENABLE_SERIES=1",
    "SQLITE_ENABLE_UUID=1",
    "SQLITE_TEMP_STORE=2",
    "SQLITE_USE_URI=1",
    "SQLITE_USER_AUTHENTICATION=1"
  }

  -- Intermediate directory
  if (is_msvc) then
    objdir (BUILDDIR .. "/obj/" .. vc_with_ver)
  else
    objdir (BUILDDIR .. "/obj/gcc")
  end
  -- Target directory
  filter { "configurations:Debug*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/dll/debug")
    else
      targetdir "bin/gcc/dll/debug"
    end
  filter { "configurations:Release*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/dll/release")
    else
      targetdir "bin/gcc/dll/release"
    end

-- SQLite3 Shell with ICU support   
project "sqlite3mc_shellicu"
  kind "ConsoleApp"
  language "C++"

  if (is_msvc) then
    local prj = project()
    prj.filename = "SQLite3MultipleCiphers_" .. vc_with_ver .. "_shellicu"
  else
    toolset("gcc")
  end
  makesettings { "include config.gcc" }

  vpaths {
    ["Header Files"] = { "**.h" },
    ["Source Files"] = { "**.c", "**.rc" }
  }
  files { "src/sqlite3.h", "src/shell.c", "src/sqlite3mc_shell.rc" }
  characterset ("Unicode")
  staticruntime "On"  
  links { "sqlite3mc_libicu" }

  filter { "platforms:Win32" }
    libdirs { "$(LIBICU_PATH)/lib" }  
  filter { "platforms:Win64" }
    libdirs { "$(LIBICU_PATH)/lib64" }  
  filter {}

  filter { "configurations:Debug*" }
    links { "icuind", "icuucd" }
  filter { "configurations:Release*" }
    links { "icuin", "icuuc" }
  filter {}

  location( BUILDDIR )

  defines {
    "SQLITE_SHELL_IS_UTF8=1",
    "SQLITE_USER_AUTHENTICATION=1"
  }

  -- Intermediate directory
  if (is_msvc) then
    objdir (BUILDDIR .. "/obj/" .. vc_with_ver)
  else
    objdir (BUILDDIR .. "/obj/gcc")
  end
  -- Target directory
  filter { "configurations:Debug*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/lib/debug")
    else
      targetdir "bin/gcc/lib/debug"
    end
  filter { "configurations:Release*" }
    if (is_msvc) then
      targetdir ("bin/" .. vc_with_ver .. "/lib/release")
    else
      targetdir "bin/gcc/lib/release"
    end
