--- ext/wasm/GNUmakefile	2026-05-05 12:34:17.000000000 +0200
+++ ext/wasm/GNUmakefile	2026-05-06 09:31:12.361566652 +0200
@@ -413,7 +413,7 @@
 # Currently always needed but TODO is paring tester1.c-pp.js down
 # to be able to run without this:
 #
-SQLITE_OPT.common += -DSQLITE_WASM_ENABLE_C_TESTS
+SQLITE_OPT.common += -DSQLITE_WASM_ENABLE_C_TESTS -D__WASM__
 
 #
 # Extra flags for full-featured builds...
@@ -571,7 +571,7 @@
 	$(CC) -O0 -o $@ libcmpp.c $(dir.top)/sqlite3.c -I$(dir.top) \
 		-DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_UTF16 \
 		-DSQLITE_OMIT_SHARED_CACHE -DSQLITE_OMIT_WAL -DSQLITE_THREADSAFE=0 \
-		-DSQLITE_TEMP_STORE=3 \
+		-DSQLITE_TEMP_STORE=3 -D__WASM__ \
 		'-DCMPP_DEFAULT_DELIM="//#"' -DCMPP_MAIN -DCMPP_OMIT_D_MODULE \
 		-DCMPP_OMIT_D_PIPE
 DISTCLEAN_FILES += $(bin.c-pp)
