#ifndef SQLITE3MC_VERSION_MAJOR
#define SQLITE3MC_VERSION_MAJOR      2
#endif

#ifndef SQLITE3MC_VERSION_MINOR
#define SQLITE3MC_VERSION_MINOR      3
#endif

#ifndef SQLITE3MC_VERSION_RELEASE
#define SQLITE3MC_VERSION_RELEASE    6
#endif

#ifndef SQLITE3MC_VERSION_SUBRELEASE
#define SQLITE3MC_VERSION_SUBRELEASE 0
#endif
